"""Golden-plan regression battery.

    python scripts/plan_battery.py --check                    # compare against tests/golden/plan_battery.json (exit 1 on drift)
    python scripts/plan_battery.py --update                   # rewrite the golden for every group
    python scripts/plan_battery.py --update --groups census   # rewrite only some groups
    python scripts/plan_battery.py --show "land area of Denver"   # print one plan (against the fixture database)

The battery plans each question in ``tests/plan_battery_queries.py`` against the small synthetic census fixture
(``tests/census_fixture.py``) and records ``QueryPlan.render()`` - the exact text the SQL model is shown.  A change in
that text for a question you did not mean to affect is a collision between datasets or concepts; the diff tells you
which question and which line.  Nothing here touches the real ``data/`` directory.
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GOLDEN = ROOT / "tests" / "golden" / "plan_battery.json"
for p in (ROOT, ROOT / "tests"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))


def run_battery(groups=None) -> dict[str, dict[str, list[str]]]:
    import census_fixture
    from plan_battery_queries import GROUPS

    fx = census_fixture.activate(Path(tempfile.mkdtemp(prefix="plan_battery_")))
    try:
        from agents.query_planner import build_query_plan
        return {g: {q: build_query_plan(q).render().splitlines() for q in qs}
                for g, qs in GROUPS.items() if not groups or g in groups}
    finally:
        census_fixture.deactivate(fx)


def load_golden() -> dict:
    return json.loads(GOLDEN.read_text(encoding="utf-8")) if GOLDEN.exists() else {}


def diff(actual: dict, golden: dict, groups=None) -> list[str]:
    out = []
    for g, plans in actual.items():
        for q, lines in plans.items():
            want = golden.get(g, {}).get(q)
            if want is None:
                out.append(f"[{g}] NEW QUESTION not in the golden: {q!r}")
            elif want != lines:
                out.append(f"[{g}] plan changed for {q!r}:\n" + "\n".join(
                    difflib.unified_diff(want, lines, "golden", "now", lineterm="", n=0)))
    for g, plans in golden.items():
        if g.startswith("_") or (groups and g not in groups):
            continue
        out.extend(f"[{g}] question removed from the battery: {q!r}" for q in plans if q not in actual.get(g, {}))
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--update", action="store_true")
    mode.add_argument("--show", metavar="QUESTION")
    ap.add_argument("--groups", help="comma-separated subset of groups")
    args = ap.parse_args(argv)
    groups = set(args.groups.split(",")) if args.groups else None

    if args.show:
        import census_fixture
        fx = census_fixture.activate(Path(tempfile.mkdtemp(prefix="plan_battery_")))
        try:
            from agents.query_planner import build_query_plan
            print(build_query_plan(args.show).render())
        finally:
            census_fixture.deactivate(fx)
        return 0

    actual = run_battery(groups)
    if args.update:
        golden = load_golden()
        golden.update(actual)
        golden["_note"] = ("Generated by scripts/plan_battery.py. 'unrelated' and 'near_miss' were generated from the code "
                           "before the census hardening: they are the zero-drift contract.")
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(json.dumps(golden, indent=1, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
        print(f"updated {GOLDEN.relative_to(ROOT)} ({', '.join(f'{g}: {len(p)}' for g, p in actual.items())})")
        return 0
    problems = diff(actual, load_golden(), groups)
    print("\n".join(problems) if problems else f"plan battery OK ({sum(len(p) for p in actual.values())} questions)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
